name: 'Setup Typst and build PDFs'
description: 'Install dependencies and build Typst PDFs.'
runs:
  using: 'composite'
  steps:
    - name: Disable cargo progress
      shell: bash
      run: |
        set -euo pipefail
        echo "CARGO_TERM_PROGRESS_WHEN=${CARGO_TERM_PROGRESS_WHEN:-never}" >> "$GITHUB_ENV"

    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-

    - name: Install Typst
      shell: bash
      run: |
        set -euo pipefail
        if ! command -v typst >/dev/null 2>&1; then
          cargo install typst-cli --locked --quiet
        fi

    - name: Install Latin Modern fonts
      shell: bash
      run: |
        set -euo pipefail
        if command -v fc-list >/dev/null 2>&1 && fc-list | grep -qi "Latin Modern"; then
          echo "Latin Modern fonts already installed"
          exit 0
        fi

        sudo apt-get update
        sudo apt-get install -y fontconfig fonts-lmodern

    - name: Compile Typst PDFs with canonical names
      shell: bash
      run: |
        set -euo pipefail
        shopt -s nullglob

        rm -f typst/en/*.pdf typst/ru/*.pdf

        for src in typst/en/*.typ typst/ru/*.typ; do
          stem="${src%.typ}"
          if [[ "$stem" == *_dark ]]; then
            dest="${stem}.pdf"
          else
            dest="${stem}_light.pdf"
          fi

          echo "Compiling $src -> $dest"
          typst compile --root . "$src" "$dest"
        done

    - name: Validate canonical PDF outputs
      shell: bash
      run: |
        set -euo pipefail

        expected=(
          typst/en/Belyakov_en_light.pdf
          typst/en/Belyakov_en_dark.pdf
          typst/ru/Belyakov_ru_light.pdf
          typst/ru/Belyakov_ru_dark.pdf
          typst/en/Belyakov_rustdev_en_light.pdf
          typst/en/Belyakov_rustdev_en_dark.pdf
          typst/ru/Belyakov_rustdev_ru_light.pdf
          typst/ru/Belyakov_rustdev_ru_dark.pdf
          typst/en/Belyakov_cto_en_light.pdf
          typst/en/Belyakov_cto_en_dark.pdf
          typst/ru/Belyakov_cto_ru_light.pdf
          typst/ru/Belyakov_cto_ru_dark.pdf
        )

        for pdf in "${expected[@]}"; do
          test -s "$pdf"
          head -c 4 "$pdf" | grep -q '%PDF'
        done

        actual_count=$(find typst -maxdepth 2 -type f -name '*.pdf' | wc -l)
        if [ "$actual_count" -ne 12 ]; then
          echo "Expected exactly 12 canonical PDFs, found $actual_count" >&2
          exit 1
        fi
