name: 'Setup Rust toolchain and cache'
description: 'Install Rust toolchain and cache cargo artifacts.'
runs:
  using: 'composite'
  steps:
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable

    - name: Cache cargo registry and target
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
          sitegen/target
        key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
