name: 'Setup Typst and build PDFs'
description: 'Install dependencies and build Typst PDFs.'
runs:
  using: 'composite'
  steps:
    - name: Cache cargo
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ~/.cargo/bin
        key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-
    - name: Install Typst
      shell: bash
      run: cargo install typst-cli --locked
    - name: Build Typst English PDF
      shell: bash
      run: typst compile typst/en/Belyakov_en.typ typst/en/Belyakov_en.pdf
    - name: Build Typst Russian PDF
      shell: bash
      run: typst compile typst/ru/Belyakov_ru.typ typst/ru/Belyakov_ru.pdf
    - name: Build role-based Typst PDFs
      shell: bash
      run: |
        for role in tl em hod tech; do
          name=$(grep "^$role =" roles.toml | cut -d '"' -f2)
          sed "s/Rust Team Lead/$name/" typst/en/Belyakov_en.typ > temp.typ
          typst compile temp.typ "typst/en/Belyakov_en_${role}.pdf"
          sed "s/Rust Team Lead/$name/" typst/ru/Belyakov_ru.typ > temp.typ
          typst compile temp.typ "typst/ru/Belyakov_ru_${role}.pdf"
        done
        rm temp.typ
