name: 'Setup LaTeX and Typst and build PDFs'
description: 'Install dependencies and build both LaTeX and Typst PDFs.'
runs:
  using: 'composite'
  steps:
    - name: Cache APT packages
      id: apt-cache
      uses: actions/cache@v3
      with:
        path: |
          /var/cache/apt/archives
          /var/lib/apt/lists
        key: ${{ runner.os }}-apt-latex-${{ hashFiles('.github/actions/setup-cv/action.yml') }}
        restore-keys: ${{ runner.os }}-apt-latex-
    - name: Install LaTeX packages
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-latex-recommended texlive-latex-extra \
          texlive-fonts-recommended texlive-lang-cyrillic latexmk
    - name: Install Typst
      shell: bash
      run: cargo install typst-cli --locked
    - name: Build English PDF
      shell: bash
      working-directory: latex/en
      run: latexmk -pdf -quiet Belyakov_en.tex
    - name: Build Russian PDF
      shell: bash
      working-directory: latex/ru
      run: latexmk -pdf -quiet Belyakov_ru.tex
    - name: Build Typst English PDF
      shell: bash
      run: typst compile typst/en/Belyakov_en.typ typst/en/Belyakov_en.pdf
    - name: Build Typst Russian PDF
      shell: bash
      run: typst compile typst/ru/Belyakov_ru.typ typst/ru/Belyakov_ru.pdf
    - name: Build role-based Typst PDFs
      shell: bash
      run: |
        for role in tl em hod tech; do
          name=$(grep "^$role =" roles.toml | cut -d '"' -f2)
          sed "s/Rust Team Lead/$name/" typst/en/Belyakov_en.typ > temp.typ
          typst compile temp.typ "typst/en/Belyakov_en_${role}.pdf"
          sed "s/Rust Team Lead/$name/" typst/ru/Belyakov_ru.typ > temp.typ
          typst compile temp.typ "typst/ru/Belyakov_ru_${role}.pdf"
        done
        rm temp.typ
