name: Auto Merge PRs

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

jobs:
  automerge:
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'neutral' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Enable auto-merge (rebase)
        id: enable_rebase
        uses: peter-evans/enable-pull-request-automerge@v3
        continue-on-error: true
        with:
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: rebase
      - name: Enable auto-merge (merge)
        if: steps.enable_rebase.outcome == 'failure'
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.workflow_run.pull_requests[0].number }}
          merge-method: merge
