name: Auto Merge PRs

on:
  workflow_run:
    workflows: ["PR Checks"]
    types:
      - completed

jobs:
  automerge:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Merge pull request if all checks pass
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.workflow_run.pull_requests[0];
            if (!pr) {
              core.info('No pull request associated with this run.');
              return;
            }
            const { owner, repo } = context.repo;
            const fullPr = await github.rest.pulls.get({
              owner,
              repo,
              pull_number: pr.number
            });
            const allowedAuthors = ['qqrm'];
            if (!allowedAuthors.includes(fullPr.data.user.login)) {
              core.info(`PR author ${fullPr.data.user.login} is not allowed to auto-merge.`);
              return;
            }
            const sha = context.payload.workflow_run.head_sha;
            const checks = await github.rest.checks.listForRef({ owner, repo, ref: sha });
            const failed = checks.data.check_runs.some(c => ['failure', 'cancelled', 'timed_out'].includes(c.conclusion));
            if (failed) {
              core.info('Some checks failed. Skipping merge.');
              return;
            }
            await github.rest.pulls.merge({
              owner,
              repo,
              pull_number: pr.number,
              merge_method: 'rebase'
            });

