name: Build Typst PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'typst/**/*.typ'
  pull_request:
    paths:
      - 'typst/**/*.typ'

jobs:
  build:
    if: github.event_name == 'push' || github.event.pull_request.user.login == 'qqrm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-cv
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            typst/en/Belyakov_en.pdf
            typst/ru/Belyakov_ru.pdf
