name: Build CV PDFs with TypePDF

on:
  workflow_dispatch:

jobs:
  build:
    if: github.actor == 'qqrm'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
          key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install TypePDF
        run: cargo install typepdf --locked
      - name: Build English PDF with TypePDF
        run: typepdf typst/en/Belyakov_en.typ typst/en/Belyakov_en_typepdf.pdf
      - name: Build Russian PDF with TypePDF
        run: typepdf typst/ru/Belyakov_ru.typ typst/ru/Belyakov_ru_typepdf.pdf
      - name: Upload PDFs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: typepdf-pdfs
          path: |
            typst/en/Belyakov_en_typepdf.pdf
            typst/ru/Belyakov_ru_typepdf.pdf
