name: Build CV PDFs

on:
  push:
    paths:
      - 'latex/**.tex'
      - 'typst/**.typ'
      - '.github/workflows/build_pdf.yml'
  pull_request:
    paths:
      - 'latex/**.tex'
      - 'typst/**.typ'
      - '.github/workflows/build_pdf.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-cv
      - name: Prepare release PDFs
        run: |
          cp latex/en/Belyakov_en.pdf latex/en/Belyakov_en_latex.pdf
          cp latex/ru/Belyakov_ru.pdf latex/ru/Belyakov_ru_latex.pdf
          cp typst/en/Belyakov_en.pdf typst/en/Belyakov_en_typst.pdf
          cp typst/ru/Belyakov_ru.pdf typst/ru/Belyakov_ru_typst.pdf
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            latex/en/Belyakov_en_latex.pdf
            latex/ru/Belyakov_ru_latex.pdf
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf
