name: Build Typst PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'typst/**/*.typ'
  pull_request:
    paths:
      - 'typst/**/*.typ'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Security check
        id: security
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            if [ "${{ github.event.pull_request.user.login }}" = "QQRM" ]; then
              echo "authorized=true" >> "$GITHUB_OUTPUT"
            else
              echo "authorized=false" >> "$GITHUB_OUTPUT"
            fi
          else
            echo "authorized=true" >> "$GITHUB_OUTPUT"
          fi
      - name: Skip untrusted PR
        if: steps.security.outputs.authorized != 'true'
        run: echo "Pipeline disabled for untrusted author."
      - uses: ./.github/actions/setup-cv
        if: steps.security.outputs.authorized == 'true'
      - name: Upload PDFs
        if: steps.security.outputs.authorized == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            typst/en/Belyakov_en.pdf
            typst/ru/Belyakov_ru.pdf
