name: Build

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            sitegen/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Install Typst CLI
        run: cargo install typst-cli --locked
      - name: Build app
        run: cargo build --release --manifest-path sitegen/Cargo.toml
      - name: Run tests
        run: cargo test --manifest-path sitegen/Cargo.toml
      - name: Validate input files
        run: cargo run --release --manifest-path sitegen/Cargo.toml --bin sitegen -- validate
      - name: Generate PDFs and HTML
        run: cargo run --release --manifest-path sitegen/Cargo.toml --bin sitegen -- generate
      - name: Check generated files
        run: |
          ls dist/
          find dist -type f -size 0 -print && exit 1 || true
