name: Build Rust Site

on:
  push:
    paths:
      - 'README.md'
      - 'README_ru.md'
      - 'style.css'
      - 'generate_site.py'
      - 'sitegen/**'
      - '.github/workflows/build_site.yml'
  pull_request:
    paths:
      - 'README.md'
      - 'README_ru.md'
      - 'style.css'
      - 'generate_site.py'
      - 'sitegen/**'
      - '.github/workflows/build_site.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
      - name: Generate site
        run: cargo run --manifest-path sitegen/Cargo.toml
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: .
      - name: Upload generated index.html
        uses: actions/upload-artifact@v4
        with:
          name: index-html
          path: index.html
