name: Build CV PDFs with TypePDF

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Install TypePDF
        run: cargo install typepdf --locked
      - name: Build English PDF with TypePDF
        run: typepdf typst/en/Belyakov_en.typ typst/en/Belyakov_en_typepdf.pdf
      - name: Build Russian PDF with TypePDF
        run: typepdf typst/ru/Belyakov_ru.typ typst/ru/Belyakov_ru_typepdf.pdf
      - name: Upload PDFs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: typepdf-pdfs
          path: |
            typst/en/Belyakov_en_typepdf.pdf
            typst/ru/Belyakov_ru_typepdf.pdf
