name: Build PDFs

on:
  push:
    branches: [ main ]
    paths:
      - 'latex/**/*.tex'
      - 'typst/**/*.typ'
  pull_request:
    paths:
      - 'latex/**/*.tex'
      - 'typst/**/*.typ'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/setup-cv
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs
          path: |
            latex/en/Belyakov_en.pdf
            latex/ru/Belyakov_ru.pdf
            typst/en/Belyakov_en.pdf
            typst/ru/Belyakov_ru.pdf
            latex/en/Belyakov_en_manager.pdf
            latex/ru/Belyakov_ru_manager.pdf
            typst/en/Belyakov_en_manager.pdf
            typst/ru/Belyakov_ru_manager.pdf
