name: Cancel PR Checks on Merge

on:
  pull_request:
    types: [closed]

jobs:
  cancel:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;
            const sha = pr.head.sha;

            const runs = await github.rest.actions.listWorkflowRunsForRepo({
              owner,
              repo,
              per_page: 100,
            });

            for (const run of runs.data.workflow_runs) {
              if (run.head_sha === sha && ['queued', 'in_progress'].includes(run.status)) {
                github.rest.actions.cancelWorkflowRun({
                  owner,
                  repo,
                  run_id: run.id,
                });
              }
            }

