name: ci

permissions:
  contents: read
  actions: write

on:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-cv
      - name: Cargo build
        run: cargo build --manifest-path sitegen/Cargo.toml
      - name: Cargo test
        run: cargo test --manifest-path sitegen/Cargo.toml
      - name: Generate site
        run: cargo run --manifest-path sitegen/Cargo.toml --bin sitegen -- generate
      - name: Verify generated artifacts
        run: |
          test -s dist/index.html
          test -s dist/ru/index.html
      - name: Upload Typst PDFs
        uses: actions/upload-artifact@v4
        with:
          name: typst-pdfs
          path: typst/**/*.pdf
