name: hh-publish

on:
  workflow_dispatch:
    inputs:
      publish:
        description: Upload payloads to HeadHunter after generating them
        type: boolean
        default: false

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate HH payloads
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p hh_payloads
          payloads=(
            "resume_ru:CV_RU.MD"
            "resume_pm_ru:CV_PM_RU.MD"
            "resume_en:CV.MD"
          )
          for entry in "${payloads[@]}"; do
            IFS=":" read -r name source <<<"$entry"
            output="hh_payloads/${name}.json"
            echo "Rendering ${source} -> ${output}"
            cargo run --manifest-path scripts/convert_cv/Cargo.toml -- "$source" > "$output"
          done

      - name: Upload payload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hh-payloads
          path: hh_payloads

      - name: Summarize generated payloads
        shell: bash
        run: |
          if [[ -n "${GITHUB_STEP_SUMMARY:-}" ]]; then
            echo "### Generated HeadHunter payloads" >> "$GITHUB_STEP_SUMMARY"
            ls -1 hh_payloads >> "$GITHUB_STEP_SUMMARY"
          fi

  publish:
    needs: generate
    if: ${{ inputs.publish }}
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - uses: actions/checkout@v4

      - name: Download payload artifact
        uses: actions/download-artifact@v4
        with:
          name: hh-payloads
          path: hh_payloads

      - name: Refresh access token
        id: token
        shell: bash
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          set -euo pipefail
          response=$(curl -sS -X POST https://hh.ru/oauth/token \
            -d grant_type=refresh_token \
            -d client_id="${CLIENT_ID}" \
            -d client_secret="${CLIENT_SECRET}" \
            -d refresh_token="${REFRESH_TOKEN}")
          token=$(echo "$response" | jq -r '.access_token')
          if [[ -z "$token" || "$token" == "null" ]]; then
            echo "Unable to extract access token" >&2
            exit 1
          fi
          echo "::add-mask::$token"
          echo "access_token=$token" >> "$GITHUB_OUTPUT"

      - name: Upload resumes to HeadHunter
        shell: bash
        env:
          ACCESS_TOKEN: ${{ steps.token.outputs.access_token }}
          RESUME_ID_RU: ${{ secrets.RESUME_ID_RU }}
          RESUME_ID_PM_RU: ${{ secrets.RESUME_ID_PM_RU }}
          RESUME_ID_EN: ${{ secrets.RESUME_ID_EN }}
        run: |
          set -uo pipefail
          summary_file="${GITHUB_STEP_SUMMARY:-}"
          if [[ -n "$summary_file" ]]; then
            echo "### Upload results" >> "$summary_file"
          fi
          entries=(
            "$RESUME_ID_RU:resume_ru.json:Russian resume"
            "$RESUME_ID_PM_RU:resume_pm_ru.json:Russian PM resume"
            "$RESUME_ID_EN:resume_en.json:English resume"
          )
          status=0
          for entry in "${entries[@]}"; do
            IFS=":" read -r resume_id file label <<<"$entry"
            if [[ -z "$resume_id" ]]; then
              echo "Skipping ${label}: resume id is not configured" >&2
              if [[ -n "$summary_file" ]]; then
                echo "- ⚠️ ${label} (missing RESUME_ID)" >> "$summary_file"
              fi
              continue
            fi
            payload="hh_payloads/${file}"
            if [[ ! -f "$payload" ]]; then
              echo "Payload ${payload} is missing" >&2
              status=1
              if [[ -n "$summary_file" ]]; then
                echo "- ❌ ${label} (payload missing)" >> "$summary_file"
              fi
              continue
            fi
            echo "Uploading ${label} (${resume_id})"
            if curl -sS -X PUT "https://api.hh.ru/resumes/${resume_id}" \
                -H "Authorization: Bearer ${ACCESS_TOKEN}" \
                -H "Content-Type: application/json" \
                --data "@${payload}" \
                --fail > /dev/null; then
              if [[ -n "$summary_file" ]]; then
                echo "- ✅ ${label}" >> "$summary_file"
              fi
            else
              echo "Failed to upload ${label}" >&2
              status=1
              if [[ -n "$summary_file" ]]; then
                echo "- ❌ ${label}" >> "$summary_file"
              fi
            fi
          done
          exit $status

