name: Manual Build CV PDFs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set build date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - uses: ./.github/actions/setup-cv
      - name: Prepare release PDFs
        run: |
          cp typst/en/Belyakov_en.pdf typst/en/Belyakov_en_typst.pdf
          cp typst/ru/Belyakov_ru.pdf typst/ru/Belyakov_ru_typst.pdf
      - name: Upload PDFs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cv-pdfs-${{ env.DATE }}
          path: |
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf

