name: Manual Build CV PDFs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Set build date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Insert build date
        run: |
          sed -i '/^\\author/a \\date{'"$DATE"'}' latex/en/Belyakov_en.tex
          sed -i '/^\\author/a \\date{'"$DATE"'}' latex/ru/Belyakov_ru.tex
      - uses: ./.github/actions/setup-cv
      - name: Prepare release PDFs
        run: |
          cp latex/en/Belyakov_en.pdf latex/en/Belyakov_en_latex.pdf
          cp latex/ru/Belyakov_ru.pdf latex/ru/Belyakov_ru_latex.pdf
          cp latex/en/Belyakov_en_manager.pdf latex/en/Belyakov_en_manager_latex.pdf
          cp latex/ru/Belyakov_ru_manager.pdf latex/ru/Belyakov_ru_manager_latex.pdf
          cp typst/en/Belyakov_en_manager.pdf typst/en/Belyakov_en_manager_typst.pdf
          cp typst/ru/Belyakov_ru_manager.pdf typst/ru/Belyakov_ru_manager_typst.pdf
          cp typst/en/Belyakov_en.pdf typst/en/Belyakov_en_typst.pdf
          cp typst/ru/Belyakov_ru.pdf typst/ru/Belyakov_ru_typst.pdf
      - name: Upload PDFs
        uses: actions/upload-artifact@v4.6.2
        with:
          name: cv-pdfs-${{ env.DATE }}
          path: |
            latex/en/Belyakov_en_latex.pdf
            latex/ru/Belyakov_ru_latex.pdf
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf
            latex/en/Belyakov_en_manager_latex.pdf
            latex/ru/Belyakov_ru_manager_latex.pdf
            typst/en/Belyakov_en_manager_typst.pdf
            typst/ru/Belyakov_ru_manager_typst.pdf

