name: Manual Build CV PDFs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set build date
        id: date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Insert build date
        run: |
          sed -i '/^\\author/a \\date{'"$DATE"'}' latex/en/Belyakov_en.tex
          sed -i '/^\\author/a \\date{'"$DATE"'}' latex/ru/Belyakov_ru.tex
      - uses: ./.github/actions/setup-cv
      - name: Upload PDFs
        uses: actions/upload-artifact@v4
        with:
          name: cv-pdfs-${{ env.DATE }}
          path: |
            latex/en/Belyakov_en.pdf
            latex/ru/Belyakov_ru.pdf
            typst/en/Belyakov_en.pdf
            typst/ru/Belyakov_ru.pdf

