name: pdf-pdfcpu

permissions:
  contents: read

on:
  push:
  pull_request:

jobs:
  pdfcpu-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Install pdfcpu
        run: go install github.com/pdfcpu/pdfcpu/v3/cmd/pdfcpu@latest
      - name: Validate PDFs
        run: |
          mkdir -p reports
          shopt -s nullglob
          for pdf in docs/*.pdf; do
            pdfcpu validate -mode strict "$pdf" > "reports/$(basename "$pdf" .pdf).txt"
          done
      - name: Upload reports
        uses: actions/upload-artifact@v4.6.2
        with:
          name: pdfcpu-reports
          path: reports
