name: qpdf check

on:
  push:
  pull_request:

jobs:
  qpdf-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install qpdf
        run: |
          sudo apt-get update
          sudo apt-get install -y qpdf
      - name: Run qpdf checks
        run: |
          mkdir -p reports
          shopt -s nullglob
          status=0
          for pdf in docs/*.pdf; do
            echo "Checking $pdf"
            qpdf --check "$pdf" > "reports/$(basename "$pdf").log" || status=1
          done
          exit $status
      - name: Upload qpdf reports
        uses: actions/upload-artifact@v4
        with:
          name: qpdf-reports
          path: reports
