name: release

permissions:
  contents: read

env:
  CARGO_TERM_PROGRESS_WHEN: never

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_sitegen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sitegen/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build
        run: cargo build --release --manifest-path sitegen/Cargo.toml --quiet
      - uses: ./.github/actions/build-pdfs
      - name: Verify PDFs
        run: |
          for lang in en ru; do
            for file in Belyakov_${lang}.pdf Belyakov_pm_${lang}.pdf; do
              if head -c 4 "typst/$lang/$file" | grep -q '%PDF'; then
                echo "$file verified";
              else
                echo "typst/$lang/$file is not recognized as a PDF" >&2;
                exit 1;
              fi;
            done;
          done;
      - name: Prepare release PDFs
        run: |
          cp typst/en/Belyakov_pm_en.pdf typst/en/Belyakov_pm_full_en.pdf;
          cp typst/ru/Belyakov_pm_ru.pdf typst/ru/Belyakov_pm_full_ru.pdf;
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitegen-assets
          path: |
            sitegen/target/release/generate
            typst/en/Belyakov_en.pdf
            typst/ru/Belyakov_ru.pdf
            typst/en/Belyakov_pm_full_en.pdf
            typst/ru/Belyakov_pm_full_ru.pdf
            typst/en/Belyakov_en_tl.pdf
            typst/en/Belyakov_en_em.pdf
            typst/en/Belyakov_en_hod.pdf
            typst/en/Belyakov_en_tech.pdf
            typst/ru/Belyakov_ru_tl.pdf
            typst/ru/Belyakov_ru_em.pdf
            typst/ru/Belyakov_ru_hod.pdf
            typst/ru/Belyakov_ru_tech.pdf

  site:
    needs: build_sitegen
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Download built assets
        uses: actions/download-artifact@v4
        with:
          name: sitegen-assets
      - name: Move sitegen binary
        run: mv sitegen/target/release/generate ./sitegen_bin
      - name: Make binary executable
        run: chmod +x sitegen_bin
      - name: Clean previous site output
        run: |
          rm -rf docs;
          rm -rf dist;
      - name: Generate site
        run: ./sitegen_bin
      - name: Verify role pages
        run: |
          test -s dist/tl/ru/index.html;
          test -s dist/resume/pm/index.html;
          test -s dist/resume/pm/ru/index.html;
      - name: Prepare Pages directory
        run: mv dist docs
      - name: Copy README_RU
        run: |
          cp README_RU.MD docs/;
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: Delete previous releases
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ids=$(gh api repos/${{ github.repository }}/releases --jq '.[].id');
          echo "$ids" | tail -n +2 | while read id; do
            gh api repos/${{ github.repository }}/releases/$id -X DELETE;
          done;
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: sitegen-${{ github.run_number }}
          files: |
            sitegen_bin
            typst/en/Belyakov_en.pdf
            typst/ru/Belyakov_ru.pdf
            typst/en/Belyakov_pm_full_en.pdf
            typst/ru/Belyakov_pm_full_ru.pdf
            typst/en/Belyakov_en_tl.pdf
            typst/en/Belyakov_en_em.pdf
            typst/en/Belyakov_en_hod.pdf
            typst/en/Belyakov_en_tech.pdf
            typst/ru/Belyakov_ru_tl.pdf
            typst/ru/Belyakov_ru_em.pdf
            typst/ru/Belyakov_ru_hod.pdf
            typst/ru/Belyakov_ru_tech.pdf
