name: Release

on:
  push:
    branches: [main]
    paths:
      - 'sitegen/**'
      - 'content/**'
      - 'docs/**'
      - 'latex/**/*.tex'
      - 'typst/**/*.typ'
      - 'Cargo.toml'
      - '.github/workflows/release.yml'
  workflow_dispatch:

jobs:
  build_sitegen:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Cache cargo registry
        uses: actions/cache@v3.4.3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sitegen/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release --manifest-path sitegen/Cargo.toml
      - uses: ./.github/actions/setup-cv
      - name: Prepare release PDFs
        run: |
          cp latex/en/Belyakov_en.pdf latex/en/Belyakov_en_latex.pdf
          cp latex/ru/Belyakov_ru.pdf latex/ru/Belyakov_ru_latex.pdf
          cp typst/en/Belyakov_en.pdf typst/en/Belyakov_en_typst.pdf
          cp typst/ru/Belyakov_ru.pdf typst/ru/Belyakov_ru_typst.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: sitegen-assets
          path: |
            sitegen/target/release/sitegen
            latex/en/Belyakov_en_latex.pdf
            latex/ru/Belyakov_ru_latex.pdf
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf

  site:
    needs: build_sitegen
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Download built assets
        uses: actions/download-artifact@v4.3.0
        with:
          name: sitegen-assets
      - name: Make binary executable
        run: chmod +x sitegen
      - name: Generate site
        run: ./sitegen
      - uses: ./.github/actions/setup-cv
      - name: Copy README_ru
        run: |
          cp README_ru.md docs/
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
      - name: Delete previous releases
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ids=$(gh api repos/${{ github.repository }}/releases --jq '.[].id')
          echo "$ids" | tail -n +2 | while read id; do
            gh api repos/${{ github.repository }}/releases/$id -X DELETE
          done
      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          tag_name: sitegen-${{ github.run_number }}
          files: |
            sitegen
            latex/en/Belyakov_en_latex.pdf
            latex/ru/Belyakov_ru_latex.pdf
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf
