name: release

permissions:
  contents: read

env:
  CARGO_TERM_PROGRESS_WHEN: never

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_sitegen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sitegen/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release --manifest-path sitegen/Cargo.toml --quiet
      - uses: ./.github/actions/setup-cv
      - name: Verify PDFs
        run: |
          for lang in en ru; do
            if file typst/$lang/Belyakov_${lang}.pdf | grep -q 'PDF document'; then
              echo "$lang PDF verified"
            else
              echo "typst/$lang/Belyakov_${lang}.pdf is not recognized as a PDF" >&2
              exit 1
            fi
          done
      - name: Prepare release PDFs
        run: |
          cp typst/en/Belyakov_en.pdf typst/en/Belyakov_en_typst.pdf
          cp typst/ru/Belyakov_ru.pdf typst/ru/Belyakov_ru_typst.pdf
          for role in tl em hod tech; do
            cp typst/en/Belyakov_en_${role}.pdf typst/en/Belyakov_en_${role}_typst.pdf
            cp typst/ru/Belyakov_ru_${role}.pdf typst/ru/Belyakov_ru_${role}_typst.pdf
          done
      - name: Upload artifacts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: sitegen-assets
          path: |
            sitegen/target/release/generate
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf
            typst/en/Belyakov_en_tl_typst.pdf
            typst/en/Belyakov_en_em_typst.pdf
            typst/en/Belyakov_en_hod_typst.pdf
            typst/en/Belyakov_en_tech_typst.pdf
            typst/ru/Belyakov_ru_tl_typst.pdf
            typst/ru/Belyakov_ru_em_typst.pdf
            typst/ru/Belyakov_ru_hod_typst.pdf
            typst/ru/Belyakov_ru_tech_typst.pdf

  site:
    needs: build_sitegen
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
      actions: write
    steps:
      - uses: actions/checkout@v4
      - name: Download built assets
        uses: actions/download-artifact@v4.3.0
        with:
          name: sitegen-assets
      - name: Move sitegen binary
        run: mv sitegen/target/release/generate ./sitegen_bin
      - name: Make binary executable
        run: chmod +x sitegen_bin
      - name: Clean previous site output
        run: |
          rm -rf docs
          rm -rf dist
      - name: Generate site
        run: ./sitegen_bin
      - name: Verify role pages
        run: test -s dist/tl/ru/index.html
      - name: Prepare Pages directory
        run: mv dist docs
      - name: Copy README_RU
        run: |
          cp README_RU.MD docs/
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
      - name: Delete previous releases
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ids=$(gh api repos/${{ github.repository }}/releases --jq '.[].id')
          echo "$ids" | tail -n +2 | while read id; do
            gh api repos/${{ github.repository }}/releases/$id -X DELETE
          done
      - name: Create Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          tag_name: sitegen-${{ github.run_number }}
          files: |
            sitegen_bin
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf
            typst/en/Belyakov_en_tl_typst.pdf
            typst/en/Belyakov_en_em_typst.pdf
            typst/en/Belyakov_en_hod_typst.pdf
            typst/en/Belyakov_en_tech_typst.pdf
            typst/ru/Belyakov_ru_tl_typst.pdf
            typst/ru/Belyakov_ru_em_typst.pdf
            typst/ru/Belyakov_ru_hod_typst.pdf
            typst/ru/Belyakov_ru_tech_typst.pdf
