name: Restrict PR Authors

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const allowedAuthors = ['qqrm'];
            const author = context.payload.pull_request.user.login;
            if (!allowedAuthors.includes(author)) {
              core.info(`Closing unauthorized pull request from ${author}`);
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                state: 'closed'
              });
              core.setFailed('Unauthorized pull request');
            }

