name: Restrict PR Authors

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  enforce:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const allowedAuthors = ['qqrm', 'octocat'];
            const author = context.payload.pull_request.user.login;
            if (!allowedAuthors.includes(author)) {
              core.setFailed(`Unauthorized pull request from ${author}`);
            }

