name: Build Site

on:
  push:
    paths:
      - 'README.md'
      - 'README_ru.md'
      - 'docs/style.css'
      - 'latex/**'
      - 'sitegen/**'
      - '.github/workflows/sitegen.yml'
  pull_request:
    paths:
      - 'README.md'
      - 'README_ru.md'
      - 'docs/style.css'
      - 'latex/**'
      - 'sitegen/**'
      - '.github/workflows/sitegen.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Download sitegen binary
        run: |
          curl -L -o sitegen_binary \
            "https://github.com/${{ github.repository }}/releases/latest/download/sitegen"
          chmod +x sitegen_binary
      - name: Generate site
        run: ./sitegen_binary
      - name: Install LaTeX packages
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra \
            texlive-fonts-recommended texlive-lang-cyrillic latexmk
      - name: Build English PDF
        working-directory: latex/en
        run: latexmk -pdf -quiet Belyakov_en.tex
      - name: Build Russian PDF
        working-directory: latex/ru
        run: latexmk -pdf -quiet Belyakov_ru.tex
      - name: Copy PDFs and README_ru
        run: |
          mkdir -p docs/latex/en docs/latex/ru
          cp latex/en/Belyakov_en.pdf docs/latex/en/
          cp latex/ru/Belyakov_ru.pdf docs/latex/ru/
          cp README_ru.md docs/

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: false
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
