name: Build Site

on:
  push:
    paths:
      - 'README.md'
      - 'sitegen/**'
      - '.github/workflows/sitegen.yml'
  pull_request:
    paths:
      - 'README.md'
      - 'sitegen/**'
      - '.github/workflows/sitegen.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release --manifest-path sitegen/Cargo.toml
      - name: Generate site
        run: cargo run --release --manifest-path sitegen/Cargo.toml
      - name: Upload generated index.html
        uses: actions/upload-artifact@v4
        with:
          name: index-html
          path: index.html
