name: Release Sitegen

on:
  push:
    paths:
      - 'sitegen/**'
      - 'Cargo.toml'
      - '.github/workflows/sitegen_release.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            sitegen/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('sitegen/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
      - name: Build
        run: cargo build --release --manifest-path sitegen/Cargo.toml
      - uses: ./.github/actions/setup-cv
      - name: Prepare release PDFs
        run: |
          cp latex/en/Belyakov_en.pdf latex/en/Belyakov_en_latex.pdf
          cp latex/ru/Belyakov_ru.pdf latex/ru/Belyakov_ru_latex.pdf
          cp typst/en/Belyakov_en.pdf typst/en/Belyakov_en_typst.pdf
          cp typst/ru/Belyakov_ru.pdf typst/ru/Belyakov_ru_typst.pdf
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitegen-assets
          path: |
            sitegen/target/release/sitegen
            latex/en/Belyakov_en_latex.pdf
            latex/ru/Belyakov_ru_latex.pdf
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf
      - name: Delete previous releases
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          ids=$(gh api repos/${{ github.repository }}/releases --jq '.[].id')
          echo "$ids" | tail -n +2 | while read id; do
            gh api repos/${{ github.repository }}/releases/$id -X DELETE
          done
      - name: Create Release
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: sitegen-${{ github.run_number }}
          files: |
            sitegen/target/release/sitegen
            latex/en/Belyakov_en_latex.pdf
            latex/ru/Belyakov_ru_latex.pdf
            typst/en/Belyakov_en_typst.pdf
            typst/ru/Belyakov_ru_typst.pdf

